---

- name: Install cron daemon
  pacman:
    name: cronie
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2


- name: Install GRUB configuration
  copy:
    src: etc/default/cron
    dest: /etc/default/cron
  notify:
    - restart cronie

- name: Enable cronie service
  service: name=cronie.service state=started enabled=yes
