---

- name: Install battery / thermal reader
  pacman:
    name:
      - acpi
      - thermald
      - usbutils
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2


- name: Enable thermald
  service: name=thermald state=started enabled=yes
