---
# - name: Remove conflicting packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Desktop Tools
  ansible.builtin.apt:
    name:
      - google-chrome-stable
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
