---

- name:  generate initramfs
  command: mkinitcpio --allpresets
  # mkinitcpio tries to find the fsck.overlay which does not exist.
  when: lookup('env', 'container') != 'docker'

- name: build grub config
  command: grub-mkconfig -o /boot/grub/grub.cfg

- name: restart neworkmanager
  service: name=networkmanager.service state=restarted

- name: restart sshd
  service: name=sshd.service state=restarted

- name: restart cronie
  service: name=cronie.service state=restarted
