---
# - name: Remove conflicting filemanagers
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install File Managers
  ansible.builtin.apt:
    name:
      - mc              # Midnight Commander - a powerful file manager
      - krusader        # Advanced twin-panel (commander-style) file manager for KDE
      - doublecmd-gtk   # Double Commander with GTK+ interface
      # - doublecmd-qt
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
