---
- name: Install Input Device Software
  ansible.builtin.apt:
    name:
      - solaar
    install_recommends: false
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
