---
- name: Install Media
  ansible.builtin.apt:
    name:
      - audacious     # Lightweight, open-source audio player
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
