---
# - name: Remove conflicting office packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Office Tools
  ansible.builtin.apt:
    name:
      - libreoffice           # Free and open-source office suite
      - libreoffice-plasma    # Integration of LibreOffice with the Plasma desktop
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
