---
# - name: Remove conflicting desktop tools
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Office Tools
  ansible.builtin.apt:
    name:
      - flameshot     # Powerful yet simple screenshot software
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
