---
- name: update apt cache if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

# - name: Remove conflicting packages
#   apt:
#     name:
#       - vim
#       - gvim
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install
  apt:
    name:
      - dolphin-plugins
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
