---
# - name: Remove conflicting kde packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Add KDE repository
  ansible.builtin.apt_repository:
    repo: ppa:kubuntu-ppa/backports
    state: present

- name: Install KDE Tools
  ansible.builtin.apt:
    name:
      - dolphin
      - dolphin-dev
      - dolphin-plugins
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
