---
# - name: Remove conflicting kde packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2


- name: Install KDE Tools
  ansible.builtin.apt:
    name:
      - dolphin             # KDE file manager
      - dolphin-dev         # Development files for the Dolphin file manager
      - dolphin-plugins     # Plugins for the Dolphin file manager
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
