---
# - name: Remove conflicting packages
#   ansible.builtin.apt:
#     name:
#       - vim
#       - gvim
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

# - name: Install main editors and ide
#   ansible.builtin.apt:
#     name:
#       - code
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2
