---
# - name: Remove conflicting packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Developmnet Tools
  ansible.builtin.apt:
    name:
      - clang-format
      - clang-format-14
      - cmake
      - g++
      - gcc
      - gdb
      - git
      - gperf
      - libtool
      - make
      - ninja-build
      - npm
      - openjdk-11-jdk
      - perl
      - pkg-config
      - qt5-qmake
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
