---
# - name: Remove conflicting packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Developmnet Tools
  ansible.builtin.apt:
    name:
      - autoconf
      - autoconf-archive
      - autopoint
      - binutils-dev
      - bison
      - build-essential
      - clang
      - clang-format
      - clang-tidy
      - clazy
      - clazy-tests
      - cmake
      - coreutils
      - cppcheck
      - g++
      - gcc
      - gdb
      - git
      - gperf
      - heaptrack
      - heaptrack-gui
      - libtool
      - libxml2-utils
      - lldb
      - llvm
      - make
      - mercurial
      - ninja-build
      - npm
      - openjdk-11-jdk
      - openjdk-17-jdk
      - openjdk-21-jdk
      - openjdk-8-jdk
      - perl
      - pkg-config
      - qt5-qmake
      - valgrind
      - vera++
      # - vulkan-sdk
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Libraries
  ansible.builtin.apt:
    name:
      - libbz2-dev
      - libc6-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libffi-dev
      - libgdbm-dev
      - libiberty-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - linux-libc-dev
      - zlib1g-dev
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
