---
# - name: Remove conflicting python packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Python Modules
  ansible.builtin.apt:
    name:
      - python3-dev     # Header files and a static library for Python (default)
      - python3-pip     # Python package installer
      - python3-venv    # Creation of virtual Python environments
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
