---
# - name: Remove conflicting python packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install Python Modules
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip
      - python3-venv
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
