---
- hosts: localhost
  become: true
  roles:
    ## System
    - { role: base,           tags: ['base']                            }
    - { role: browsers,       tags: ['browsers']                        }
    - { role: kde,            tags: ['kde', 'wm']                       }
    - { role: storages,       tags: ['storages', 'onedrive', 'dropbox'] }
    - { role: system,         tags: ['system']                          }
    - { role: xorg,           tags: ['xorg']                            }

    ## Development
    - { role: development,    tags: ['development']                     }
    - { role: devops,         tags: ['devops']                          }
    - { role: python,         tags: ['python']                          }
    - { role: tools,          tags: ['tools']                           }

    ## TBA
    # - { role: user,         tags: ['user']                            }
    # - { role: windows,      tags: ['windows']                         }
    # - { role: dev_tools,      tags: ['dev_tools', 'tools']            }
    # - { role: qt,             tags: ['qt']                            }
    # - { role: dev_cpp,        tags: ['dev_cpp', 'cpp']                }
    # - { role: dev_javascript, tags: ['dev_javascript', 'javascript']  }
    # - { role: dev_java,       tags: ['dev_java', 'java']              }
    # - { role: dev_haskell,    tags: ['dev_haskell', 'haskell']        }
    # - { role: dev_go,         tags: ['dev_go', 'go']                  }
    # - { role: dev_dotnet,     tags: ['dev_dotnet', 'dotnet']          }
    # - { role: devops,         tags: ['devops']                        }

    ## Virtualization
    # - { role: kvm,            tags: ['kvm']                           }
    # - { role: docker,         tags: ['docker']                        }
    # - { role: virtualbox,     tags: ['virtualbox']                    }

    # Office
    - { role: desktop,        tags: ['desktop', 'office']               }

  vars:
    user_name:  divanov
    system_hostname: divanov-dev
