---
- hosts: localhost
  become: true
  roles:
    # Initialization
    - { role: apt,          tags: ['repos']       }

    # Packages
    - { role: base,         tags: ['base']        }
    - { role: browsers,     tags: ['browsers']    }
    - { role: development,  tags: ['development'] }
    - { role: devops,       tags: ['devops']      }
    - { role: python,       tags: ['python']      }
    - { role: tools,        tags: ['tools']       }
    - { role: xorg,         tags: ['xorg']        }

    # Configuration
    - { role: system,       tags: ['system']      }
    # - { role: docker,       tags: ['docker']      }

  vars:
