---
- hosts: localhost
  become: true
  roles:
    # Base
    - { role: packages,         tags: ['packages']                          }
    - { role: system,           tags: ['system']                            }
 
    # Speicial 
    - { role: aws,              tags: ['aws', 'awscli']                     }
    - { role: cuda,             tags: ['cuda'], cuda_version: "13.3"        }
    - { role: hashicorp,        tags: ['hashicorp', 'terraform']            }
    - { role: jetbrains,        tags: ['jetbrains', 'ide']                  }
    - { role: mono,             tags: ['mono', 'certificates']              }
    - { role: kitware,          tags: ['kitware', 'cmake']                  }
    - { role: kubernetes-tools, tags: ['kubernetes', 'kubectl', 'kubectx']  }

    # Optional
    # - { role: vscode,         tags: ['vscode']                            }
    # - { role: vulkan,         tags: ['vulkan']                            }
    # - { role: docker,         tags: ['docker']                            }

  vars:
