---
# - name: Remove conflicting packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

# - name: Install DevOps Tools
#   ansible.builtin.apt:
#     name:
#       - awscli
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2
