---
- name: Add the Microsoft apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft Visual Studio Code apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: 'vscode'

- name: Install main dependancies
  pacman:
    name:
      - apt-transport-https
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Update apt cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: Remove conflicting packages
#   pacman:
#     name:
#       - vim
#       - gvim
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install main editors and ide
  pacman:
    name:
      - code
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
