---
- hosts: localhost
  become: true
  roles:
    - { role: base,         tags: ['base']        }
    - { role: tools,        tags: ['tools']       }
    - { role: python,       tags: ['python']      }
    - { role: development,  tags: ['development'] }
    - { role: xorg,         tags: ['xorg']        }

  vars:
