---
- name: Add Google Chrome repository
  block:
    - name: "Add Google Chrome repository Apt Key"
      ansible.builtin.apt_key:
        url: "https://dl.google.com/linux/linux_signing_key.pub"
        state: present

    - name: "Add Google Chrome repository"
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present

- name: Add Microsoft VS Code repository
  block:
  - name: "Add Microsoft VS Code repository Apt Key"
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: EB3E94ADBE1229CF
      state: present

  - name: "Add Microsoft VS Code repository"
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
      filename: vscode
      state: present

- name: Add Jonas Groeger unoficial JetBrains PPA repository
  block:
    - name: "Jetbrains APT Repo Key"
      ansible.builtin.apt_key:
        url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
        state: present

    - name: "Jetbrains APT Repo"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main"
        filename: jetbrains-ppa-jg
        state: present

- name: Add Kitware repository
  block:
    - name: "Kitware APT Repo Key"
      ansible.builtin.apt_key:
        url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        state: present

    - name: "Kitware APT Repo"
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kitware.com/ubuntu/ {{ ansible_distribution_release }} main"
        filename: kitware
        state: present

- name: Add LunarG Vulkan repository
  block:
    - name: "LunarG Repo Key"
      ansible.builtin.apt_key:
        url: https://packages.lunarg.com/lunarg-signing-key-pub.asc
        state: present

    - name: "Vulkan Repo"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.lunarg.com/vulkan/ {{ ansible_distribution_release }} main"
        filename: lunarg-vulkan-deb
        state: present

    - name: "Vulkan Repo SRC"
      ansible.builtin.apt_repository:
        repo: "deb-src [arch=amd64] https://packages.lunarg.com/vulkan/ {{ ansible_distribution_release }} main"
        filename: lunarg-vulkan-deb-src
        state: present

- name: Add HashiCorp repository
  block:
    - name: "HashiCorp APT Repo Key"
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: "HashiCorp APT Repo"
      ansible.builtin.apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present

- name: Update apt cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
