---
- name: Remove old OneDrive repository
  ansible.builtin.apt_repository:
    repo: ppa:yann1ck/onedrive
    state: absent

- name: Add OpenSUSE OneDrive repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/obs-onedrive.gpg] https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/ ./"
    filename: onedrive.list
    state: present

- name: Add Google repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google.list
    state: present

- name: Update apt cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
