---
- import_tasks: apt.yml

# - name: Remove conflicting base packages
#   ansible.builtin.apt:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Essential Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - apt-utils
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - dos2unix
      - fuse
      - gnome-keyring
      - jq
      - mc
      - p7zip-full
      - pciutils
      - seahorse
      - texinfo
      - unzip
      - util-linux
      - wget
      - zip
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
