---
# - name: Remove conflicting packages
#   pacman:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install IDE and Editors
  apt:
    name:
      - code
      - codeblocks
      - vim
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Remove packages
  apt:
    name:
      - clion
      - intellij-idea-ultimate
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
