---

- name: Install xorg server
  pacman:
    name:
      - xorg-server
      - xorg-server-common
      - xorg-server-devel
      - xorg-server-xephyr
      - xorg-server-xnest
      - xorg-server-xvfb
      # - xorg-server-xwayland  # for Wayland support
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install xorg drivers
  pacman:
    name:
      - xf86-video-fbdev # xorg default driver
      - xf86-video-vesa
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install xorg apps
  pacman:
    name:
      - luit
      - xorg-bdftopcf
      - xorg-docs
      - xorg-iceauth
      - xorg-mkfontscale
      - xorg-sessreg
      - xorg-setxkbmap
      - xorg-smproxy
      - xorg-x11perf
      - xorg-xauth
      - xorg-xbacklight
      - xorg-xcmsdb
      - xorg-xcursorgen
      - xorg-xdpyinfo
      - xorg-xdriinfo
      - xorg-xev
      - xorg-xfd
      - xorg-xgamma
      - xorg-xhost
      - xorg-xinit
      - xorg-xinput
      - xorg-xkbcomp
      - xorg-xkbevd
      - xorg-xkbutils
      - xorg-xkill
      - xorg-xlsatoms
      - xorg-xlsclients
      - xorg-xmodmap
      - xorg-xpr
      - xorg-xprop
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xrefresh
      - xorg-xset
      - xorg-xsetroot
      - xorg-xvinfo
      - xorg-xwd
      - xorg-xwininfo
      - xorg-xwud
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install xorg fonts
  pacman:
    name:
      - xorg-font-util
      # - xorg-font-utils - now in AUR
      - xorg-fonts-75dpi
      - xorg-fonts-100dpi
      - xorg-fonts-encodings
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: Install xorg fonts (AUR)
#   aura:
#     name:
#       - xorg-font-utils - now in AUR
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Allow Xorg to be used by anyone
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config

- name: Set default display
  lineinfile:
    dest: /etc/systemd/user.conf
    state: present
    line: "DefaultEnvironment=DISPLAY=:0"
