---
# - name: Remove conflicting tools
#   pacman:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install IDE and Editors
  apt:
    name:
      - code                      # Visual Studio Code - Code editing. Redefined.
      - codeblocks                # C, C++, and Fortran IDE
      - vim                       # Vi IMproved - enhanced vi editor
      - clion                     # Cross-platform IDE for C and C++
      - intellij-idea-ultimate    # Capable and Ergonomic IDE for JVM
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Security Tools
  apt:
    name:
      - encfs                     # Encrypted filesystem in user-space
      - gocryptfs                 # Encrypted overlay filesystem written in Go
      # - kleopatra               # Certificate manager and GUI for GnuPG
      # - scdaemon                # Smartcard daemon for GnuPG
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: Remove packages
#   apt:
#     name:
#       - clion
#       - intellij-idea-ultimate
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2
