---
# - name: Remove conflicting tools
#   pacman:
#     name:
#       - xxx
#     state: absent
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Install IDE and Editors
  apt:
    name:
      - code
      - codeblocks
      - vim
      - clion
      - intellij-idea-ultimate
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: Install Security Tools
#   apt:
#     name:
#       - gocryptfs
#       # - kleopatra
#       # - scdaemon
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2

- name: Remove packages
  apt:
    name:
      # - clion
      # - intellij-idea-ultimate
      - gocryptfs
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
