---
- name: Fix overlapping greeters on multiscreen setup
  ansible.builtin.blockinfile:
    path: /usr/share/sddm/scripts/Xsetup
    block: |
      for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
        [ -z "$current" ] && current=$next && continue
        xrandr --output $current --auto --output $next --auto --right-of $current
        current=$next
      done
