---
cuda_version: "13.0"
cuda_keyring_version: "1.1-1"
cuda_packages:
  - "cuda-{{ cuda_version | replace('.', '-') }}"
  - "cuda-nvcc-{{ cuda_version | replace('.', '-') }}"
  - "cuda-libraries-dev-{{ cuda_version | replace('.', '-') }}"
