---

- name: Install haskell tools
  pacman:
    name:
      - ghc
      - hlint
      - stack
      - hasktags
      - hoogle
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
