---

- name: Install go development tools
  pacman:
    name:
      - dotnet-runtime
      - dotnet-sdk
      - dotnet-host
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
