---
- name: Add Google Chrome repository Apt Key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4EB27DB2A3B88B8B

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present

- name: Add Microsoft VS Code repository Apt Key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: EB3E94ADBE1229CF

- name: Add Microsoft VS Code repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present

- name: Add Jonas Groeger unoficial JetBrains PPA repository
  block:
    - name: "Jetbrains APT Repo Key"
      ansible.builtin.get_url:
        url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
        dest: /etc/apt/trusted.gpg.d/jetbrains-ppa-jg.asc

    - name: "Jetbrains APT Repo"
      ansible.builtin.apt_repository:
        repo: "deb [[arch=amd64 signed-by=/etc/apt/trusted.gpg.d/jetbrains-ppa-jg.asc] http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main"
        filename: jetbrains-ppa-jg
        state: present

- name: Add Kitware repository
  block:
    - name: "Kitware APT Repo Key"
      ansible.builtin.get_url:
        url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        dest: /usr/share/keyrings/kitware-archive-latest.asc

    - name: "Kitware APT Repo"
      ansible.builtin.apt_repository:
        # repo: "deb [signed-by=/usr/share/keyrings/kitware-archive-latest.asc] https://apt.kitware.com/ubuntu/ {{ ansible_distribution_release }} main"
        repo: "deb [signed-by=/usr/share/keyrings/kitware-archive-latest.asc] https://apt.kitware.com/ubuntu/ jammy main"
        filename: kitware
        state: present

- name: Add LunarG Vulkan repository
  block:
    - name: "LunarG Repo Key"
      ansible.builtin.get_url:
        url: https://packages.lunarg.com/lunarg-signing-key-pub.asc
        dest: /etc/apt/trusted.gpg.d/lunarg.asc

    - name: "Vulkan Repo"
      ansible.builtin.apt_repository:
        repo: "deb [[arch=amd64 signed-by=/etc/apt/trusted.gpg.d/lunarg.asc] https://packages.lunarg.com/vulkan/ {{ ansible_distribution_release }} main"
        filename: lunarg-vulkan-deb
        state: present

    - name: "Vulkan Repo SRC"
      ansible.builtin.apt_repository:
        repo: "deb-src [[arch=amd64 signed-by=/etc/apt/trusted.gpg.d/lunarg.asc] https://packages.lunarg.com/vulkan/ {{ ansible_distribution_release }} main"
        filename: lunarg-vulkan-deb-src
        state: present

- name: Add HashiCorp repository
  block:
    - name: "HashiCorp APT Repo Key"
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc

    - name: "HashiCorp APT Repo"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present

- name: Add KDE repository
  ansible.builtin.apt_repository:
    repo: ppa:kubuntu-ppa/backports
    state: present

- name: Update apt cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
