---
- name: Install Network Utilities
  ansible.builtin.apt:
    name:
      - network-manager-openconnect   # OpenConnect VPN client for NetworkManager
      - network-manager-openvpn       # OpenVPN plugin for NetworkManager
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
