---
- name: Install Network Utilities
  ansible.builtin.apt:
    name:
      - network-manager-openconnect
      - network-manager-openvpn
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
