---

- name: Uninstall file managers
  pacman:
    name:
      - doublecmd-qt5
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install file managers
  pacman:
    name:
      - doublecmd-gtk2
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
