---

- name: Install VirtualBox
  pacman:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install VirtualBox extentions (AUR)
  aura:
    name:
      # - virtualbox-bin
      - virtualbox-ext-oracle
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Add user {{ user_name }} in vboxusers group
  user:
    name: "{{ user_name }}"
    groups: vboxusers
    append: yes
